resources:
- ../../base/istory-app
- ../../base/istory-db

namespace: istory-dev

patches:
- path: patch-lb-annotations.yml
  target:
    kind: Service
    name: istory-app-lb
- path: patch-deploy.yml
  target:
    kind: Deployment
    name: istory-app-deploy

# - name: dangtong76/istory
#   newTag: latest
# - name: istory
images:
- name: kubecats/istory
  newName: kubecats/istory
  newTag: "18"

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
